import type {
  Faculty,
  Department,
  Lecturer,
  Major,
  Course,
  CourseClass,
  Criterion,
  SurveyCampaign,
  SystemStats,
} from '../types';

export const initialStats: SystemStats = {
  totalFaculties: 8,
  totalMajors: 24,
  totalCourses: 156,
  totalClasses: 340,
  activeCampaigns: 3,
  totalResponses: 14280,
  overallSatisfaction: 4.68,
  qrScanCount: 18950,
};

export const initialLecturers: Lecturer[] = [
  {
    id: 'lec-1',
    code: 'CB01025',
    fullName: 'TS. Nguyễn Văn A',
    academicTitle: 'TS.',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    departmentId: 'dept-1',
    departmentName: 'Bộ môn Công nghệ Phần mềm',
    email: 'anguyen@vimaru.edu.vn',
    phone: '0912 345 678',
    specialization: 'Lập trình Web, Kiến trúc Phần mềm',
    status: 'Đang công tác',
  },
  {
    id: 'lec-2',
    code: 'CB01028',
    fullName: 'ThS. Trần Thị B',
    academicTitle: 'ThS.',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    departmentId: 'dept-2',
    departmentName: 'Bộ môn Hệ thống Thông tin & Mạng máy tính',
    email: 'btran@vimaru.edu.vn',
    phone: '0988 765 432',
    specialization: 'Cơ sở Dữ liệu, Trí tuệ Nhân tạo',
    status: 'Đang công tác',
  },
  {
    id: 'lec-3',
    code: 'CB02011',
    fullName: 'PGS. TS. Lê Văn C',
    academicTitle: 'PGS. TS.',
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    departmentId: 'dept-4',
    departmentName: 'Bộ môn Điều khiển Tàu biển',
    email: 'cle@vimaru.edu.vn',
    phone: '0903 111 222',
    specialization: 'Điều khiển Tàu biển, Luật Hàng hải',
    status: 'Đang công tác',
  },
  {
    id: 'lec-4',
    code: 'CB03045',
    fullName: 'TS. Phạm Minh D',
    academicTitle: 'TS.',
    facultyId: 'fac-3',
    facultyName: 'Khoa Kinh tế',
    departmentId: 'dept-6',
    departmentName: 'Bộ môn Logistics & Chuỗi cung ứng',
    email: 'dpham@vimaru.edu.vn',
    phone: '0977 333 444',
    specialization: 'Logistics Cảng biển, Vận tải Quốc tế',
    status: 'Đang công tác',
  },
  {
    id: 'lec-5',
    code: 'CB01099',
    fullName: 'ThS. Hoàng Thị E',
    academicTitle: 'ThS.',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    departmentId: 'dept-1',
    departmentName: 'Bộ môn Công nghệ Phần mềm',
    email: 'ehoang@vimaru.edu.vn',
    phone: '0915 888 999',
    specialization: 'Kiểm thử Phần mềm, DevOps',
    status: 'Đang công tác',
  },
];

export const initialFaculties: Faculty[] = [
  {
    id: 'fac-1',
    code: 'CNTT',
    name: 'Khoa Công nghệ Thông tin',
    dean: 'TS. Nguyễn Văn Hải',
    email: 'cntt@vimaru.edu.vn',
    phone: '0225 3829 101',
    establishedYear: 1997,
    departmentsCount: 3,
    totalCourses: 35,
    totalStudents: 1850,
  },
  {
    id: 'fac-2',
    code: 'VD',
    name: 'Viện Viễn dương (Hàng hải)',
    dean: 'PGS. TS. Trần Đức Phú',
    email: 'vienvienduong@vimaru.edu.vn',
    phone: '0225 3829 102',
    establishedYear: 1956,
    departmentsCount: 2,
    totalCourses: 42,
    totalStudents: 2400,
  },
  {
    id: 'fac-3',
    code: 'KT',
    name: 'Khoa Kinh tế',
    dean: 'TS. Phạm Thị Mai',
    email: 'kinhte@vimaru.edu.vn',
    phone: '0225 3829 103',
    establishedYear: 1984,
    departmentsCount: 2,
    totalCourses: 38,
    totalStudents: 2100,
  },
  {
    id: 'fac-4',
    code: 'DK',
    name: 'Khoa Điện - Điện tử',
    dean: 'TS. Lê Hoàng Nam',
    email: 'diendientu@vimaru.edu.vn',
    phone: '0225 3829 104',
    establishedYear: 1970,
    departmentsCount: 2,
    totalCourses: 28,
    totalStudents: 1450,
  },
  {
    id: 'fac-5',
    code: 'CK',
    name: 'Khoa Cơ khí',
    dean: 'TS. Vũ Đình Tuấn',
    email: 'cokhi@vimaru.edu.vn',
    phone: '0225 3829 105',
    establishedYear: 1956,
    departmentsCount: 2,
    totalCourses: 30,
    totalStudents: 1600,
  },
];

export const initialDepartments: Department[] = [
  {
    id: 'dept-1',
    code: 'BM-CNPM',
    name: 'Bộ môn Công nghệ Phần mềm',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    headOfDepartment: 'TS. Nguyễn Văn A',
    email: 'bmcnpm@vimaru.edu.vn',
    phone: '0225 3829 110',
    totalLecturers: 12,
    totalCourses: 14,
  },
  {
    id: 'dept-2',
    code: 'BM-HTTT',
    name: 'Bộ môn Hệ thống Thông tin & Mạng máy tính',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    headOfDepartment: 'ThS. Trần Thị B',
    email: 'bmhttt@vimaru.edu.vn',
    phone: '0225 3829 111',
    totalLecturers: 10,
    totalCourses: 12,
  },
  {
    id: 'dept-3',
    code: 'BM-KHMT',
    name: 'Bộ môn Khoa học Máy tính & AI',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    headOfDepartment: 'TS. Lê Văn C',
    email: 'bmkhmt@vimaru.edu.vn',
    phone: '0225 3829 112',
    totalLecturers: 8,
    totalCourses: 9,
  },
  {
    id: 'dept-4',
    code: 'BM-DKTB',
    name: 'Bộ môn Điều khiển Tàu biển',
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    headOfDepartment: 'PGS. TS. Lê Văn C',
    email: 'bmdktb@vimaru.edu.vn',
    phone: '0225 3829 113',
    totalLecturers: 18,
    totalCourses: 20,
  },
  {
    id: 'dept-5',
    code: 'BM-KTMT',
    name: 'Bộ môn Khai thác Máy tàu thủy',
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    headOfDepartment: 'TS. Phạm Minh D',
    email: 'bmktmt@vimaru.edu.vn',
    phone: '0225 3829 114',
    totalLecturers: 15,
    totalCourses: 16,
  },
  {
    id: 'dept-6',
    code: 'BM-LOG',
    name: 'Bộ môn Logistics & Chuỗi cung ứng',
    facultyId: 'fac-3',
    facultyName: 'Khoa Kinh tế',
    headOfDepartment: 'TS. Phạm Thị Mai',
    email: 'bmlogistics@vimaru.edu.vn',
    phone: '0225 3829 115',
    totalLecturers: 14,
    totalCourses: 18,
  },
  {
    id: 'dept-7',
    code: 'BM-KTVT',
    name: 'Bộ môn Kinh tế Vận tải biển',
    facultyId: 'fac-3',
    facultyName: 'Khoa Kinh tế',
    headOfDepartment: 'ThS. Hoàng Văn E',
    email: 'bmktvt@vimaru.edu.vn',
    phone: '0225 3829 116',
    totalLecturers: 11,
    totalCourses: 15,
  },
];

export const initialMajors: Major[] = [
  {
    id: 'maj-1',
    code: '7480101',
    name: 'Công nghệ Thông tin (Chuẩn)',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    degreeLevel: 'Đại học',
    durationYears: 4,
    totalCredits: 132,
    status: 'Đang đào tạo',
  },
  {
    id: 'maj-2',
    code: '7480201',
    name: 'Kỹ thuật Phần mềm',
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    degreeLevel: 'Đại học',
    durationYears: 4,
    totalCredits: 135,
    status: 'Đang đào tạo',
  },
  {
    id: 'maj-3',
    code: '7840101',
    name: 'Điều khiển Tàu biển (Khoa học Hàng hải)',
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    degreeLevel: 'Đại học',
    durationYears: 4.5,
    totalCredits: 148,
    status: 'Đang đào tạo',
  },
  {
    id: 'maj-4',
    code: '7840102',
    name: 'Khai thác Máy tàu thủy',
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    degreeLevel: 'Đại học',
    durationYears: 4.5,
    totalCredits: 145,
    status: 'Đang đào tạo',
  },
  {
    id: 'maj-5',
    code: '7510605',
    name: 'Logistics và Chuỗi cung ứng',
    facultyId: 'fac-3',
    facultyName: 'Khoa Kinh tế',
    degreeLevel: 'Đại học',
    durationYears: 4,
    totalCredits: 130,
    status: 'Đang đào tạo',
  },
];

export const initialCourses: Course[] = [
  {
    id: 'crs-1',
    code: 'IT201',
    name: 'Lập trình Web nâng cao & Đánh giá chất lượng',
    credits: 3,
    theoryHours: 30,
    practicalHours: 30,
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    type: 'Bắt buộc',
    description: 'Trang bị kiến thức phát triển Web ứng dụng hiện đại và các chỉ tiêu đánh giá chất lượng trải nghiệm người dùng.',
  },
  {
    id: 'crs-2',
    code: 'IT305',
    name: 'Cơ sở Dữ liệu Quan hệ & Phi quan hệ',
    credits: 4,
    theoryHours: 45,
    practicalHours: 30,
    facultyId: 'fac-1',
    facultyName: 'Khoa Công nghệ Thông tin',
    type: 'Bắt buộc',
    description: 'Thiết kế, quản trị và tối ưu hóa hệ thống CSDL lớn phục vụ bài toán khảo sát số liệu.',
  },
  {
    id: 'crs-3',
    code: 'NAV101',
    name: 'Pháp luật Hàng hải & Quốc tế',
    credits: 2,
    theoryHours: 30,
    practicalHours: 0,
    facultyId: 'fac-2',
    facultyName: 'Viện Viễn dương (Hàng hải)',
    type: 'Bắt buộc',
    description: 'Các công ước quốc tế SOLAS, MARPOL và luật hàng hải Việt Nam.',
  },
  {
    id: 'crs-4',
    code: 'LOG202',
    name: 'Quản trị Logistics Cảng biển',
    credits: 3,
    theoryHours: 30,
    practicalHours: 15,
    facultyId: 'fac-3',
    facultyName: 'Khoa Kinh tế',
    type: 'Bắt buộc',
    description: 'Quy trình khai thác cảng, quản lý chuỗi cung ứng container xuất nhập khẩu.',
  },
  {
    id: 'crs-5',
    code: 'EE104',
    name: 'Tự động hóa Tàu thủy',
    credits: 3,
    theoryHours: 30,
    practicalHours: 15,
    facultyId: 'fac-4',
    facultyName: 'Khoa Điện - Điện tử',
    type: 'Tự chọn',
    description: 'Mạch điều khiển tự động và cảm biến điều khiển hành trình tàu.',
  },
];

export const initialClasses: CourseClass[] = [
  {
    id: 'cls-1',
    code: 'IT201.01',
    courseId: 'crs-1',
    courseCode: 'IT201',
    courseName: 'Lập trình Web nâng cao & Đánh giá chất lượng',
    lecturerName: 'TS. Nguyễn Văn A',
    lecturerEmail: 'anguyen@vimaru.edu.vn',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    totalStudents: 65,
    room: 'A6-302',
    surveyStatus: 'Đang khảo sát',
    completedResponses: 58,
    groups: [
      {
        id: 'grp-101',
        classId: 'cls-1',
        groupCode: 'N01',
        fullGroupCode: 'IT201.01.N01',
        lecturerId: 'lec-1',
        lecturerName: 'TS. Nguyễn Văn A',
        lecturerEmail: 'anguyen@vimaru.edu.vn',
        studentCount: 35,
        room: 'A6-302 (PM1)',
        schedule: 'Thứ 2 (Tiết 1-3)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 32,
      },
      {
        id: 'grp-102',
        classId: 'cls-1',
        groupCode: 'N02',
        fullGroupCode: 'IT201.01.N02',
        lecturerId: 'lec-5',
        lecturerName: 'ThS. Hoàng Thị E',
        lecturerEmail: 'ehoang@vimaru.edu.vn',
        studentCount: 30,
        room: 'A6-304 (PM2)',
        schedule: 'Thứ 4 (Tiết 4-6)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 26,
      },
    ],
  },
  {
    id: 'cls-2',
    code: 'IT305.02',
    courseId: 'crs-2',
    courseCode: 'IT305',
    courseName: 'Cơ sở Dữ liệu Quan hệ & Phi quan hệ',
    lecturerName: 'ThS. Trần Thị B',
    lecturerEmail: 'btran@vimaru.edu.vn',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    totalStudents: 70,
    room: 'A6-401',
    surveyStatus: 'Đang khảo sát',
    completedResponses: 62,
    groups: [
      {
        id: 'grp-201',
        classId: 'cls-2',
        groupCode: 'N01',
        fullGroupCode: 'IT305.02.N01',
        lecturerId: 'lec-2',
        lecturerName: 'ThS. Trần Thị B',
        lecturerEmail: 'btran@vimaru.edu.vn',
        studentCount: 36,
        room: 'A6-401 (PM3)',
        schedule: 'Thứ 3 (Tiết 1-3)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 32,
      },
      {
        id: 'grp-202',
        classId: 'cls-2',
        groupCode: 'N02',
        fullGroupCode: 'IT305.02.N02',
        lecturerId: 'lec-2',
        lecturerName: 'ThS. Trần Thị B',
        lecturerEmail: 'btran@vimaru.edu.vn',
        studentCount: 34,
        room: 'A6-401 (PM3)',
        schedule: 'Thứ 5 (Tiết 7-9)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 30,
      },
    ],
  },
  {
    id: 'cls-3',
    code: 'NAV101.01',
    courseId: 'crs-3',
    courseCode: 'NAV101',
    courseName: 'Pháp luật Hàng hải & Quốc tế',
    lecturerName: 'PGS. TS. Lê Văn C',
    lecturerEmail: 'cle@vimaru.edu.vn',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    totalStudents: 120,
    room: 'Hội trường C1',
    surveyStatus: 'Đang khảo sát',
    completedResponses: 110,
    groups: [
      {
        id: 'grp-301',
        classId: 'cls-3',
        groupCode: 'N01',
        fullGroupCode: 'NAV101.01.N01',
        lecturerId: 'lec-3',
        lecturerName: 'PGS. TS. Lê Văn C',
        lecturerEmail: 'cle@vimaru.edu.vn',
        studentCount: 60,
        room: 'Hội trường C1',
        schedule: 'Thứ 6 (Tiết 1-4)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 55,
      },
      {
        id: 'grp-302',
        classId: 'cls-3',
        groupCode: 'N02',
        fullGroupCode: 'NAV101.01.N02',
        lecturerId: 'lec-3',
        lecturerName: 'PGS. TS. Lê Văn C',
        lecturerEmail: 'cle@vimaru.edu.vn',
        studentCount: 60,
        room: 'Hội trường C1',
        schedule: 'Thứ 6 (Tiết 5-8)',
        surveyStatus: 'Đang khảo sát',
        completedResponses: 55,
      },
    ],
  },
  {
    id: 'cls-4',
    code: 'LOG202.03',
    courseId: 'crs-4',
    courseCode: 'LOG202',
    courseName: 'Quản trị Logistics Cảng biển',
    lecturerName: 'TS. Phạm Minh D',
    lecturerEmail: 'dpham@vimaru.edu.vn',
    semester: 'Học kỳ I',
    academicYear: '2025-2026',
    totalStudents: 85,
    room: 'B2-204',
    surveyStatus: 'Đã hoàn thành',
    completedResponses: 85,
    groups: [
      {
        id: 'grp-401',
        classId: 'cls-4',
        groupCode: 'N01',
        fullGroupCode: 'LOG202.03.N01',
        lecturerId: 'lec-4',
        lecturerName: 'TS. Phạm Minh D',
        lecturerEmail: 'dpham@vimaru.edu.vn',
        studentCount: 45,
        room: 'B2-204',
        schedule: 'Thứ 3 (Tiết 4-6)',
        surveyStatus: 'Đã hoàn thành',
        completedResponses: 45,
      },
      {
        id: 'grp-402',
        classId: 'cls-4',
        groupCode: 'N02',
        fullGroupCode: 'LOG202.03.N02',
        lecturerId: 'lec-4',
        lecturerName: 'TS. Phạm Minh D',
        lecturerEmail: 'dpham@vimaru.edu.vn',
        studentCount: 40,
        room: 'B2-204',
        schedule: 'Thứ 5 (Tiết 1-3)',
        surveyStatus: 'Đã hoàn thành',
        completedResponses: 40,
      },
    ],
  },
];

export const initialCriteria: Criterion[] = [
  // Tiêu chí học phần
  {
    id: 'cri-1',
    category: 'Học phần',
    groupName: 'Nội dung & Mục tiêu giảng dạy',
    code: 'HP01',
    question: 'Đề cương chi tiết và chuẩn đầu ra (CLO) học phần được công bố rõ ràng ngay đầu học kỳ.',
    weight: 1.0,
    status: 'Kích hoạt',
  },
  {
    id: 'cri-2',
    category: 'Học phần',
    groupName: 'Phương pháp giảng dạy',
    code: 'HP02',
    question: 'Giảng viên ứng dụng các phương pháp giảng dạy tích cực, gợi mở tư duy và liên hệ thực tiễn ngành Hàng hải/CNTT.',
    weight: 1.0,
    status: 'Kích hoạt',
  },
  {
    id: 'cri-3',
    category: 'Học phần',
    groupName: 'Phương pháp đánh giá',
    code: 'HP03',
    question: 'Các bài kiểm tra, bài tập lớn và hình thức đánh giá công bằng, phản ánh đúng năng lực sinh viên.',
    weight: 1.0,
    status: 'Kích hoạt',
  },
  {
    id: 'cri-4',
    category: 'Học phần',
    groupName: 'Hạ tầng & Phòng thực hành',
    code: 'HP04',
    question: 'Phòng học, trang thiết bị máy tính/mô phỏng đáp ứng tốt yêu cầu thực hành học phần.',
    weight: 1.0,
    status: 'Kích hoạt',
  },

  // Tiêu chí Chương trình đào tạo
  {
    id: 'cri-5',
    category: 'Chương trình đào tạo',
    groupName: 'Mục tiêu & Chuẩn đầu ra (PLO)',
    code: 'CTDT01',
    question: 'Chương trình đào tạo đáp ứng tốt nhu cầu tuyển dụng thực tế của doanh nghiệp và ngành nghề.',
    weight: 1.2,
    status: 'Kích hoạt',
  },
  {
    id: 'cri-6',
    category: 'Chương trình đào tạo',
    groupName: 'Cấu trúc & Tính ứng dụng',
    code: 'CTDT02',
    question: 'Tỷ lệ giữa các môn lý thuyết và thực hành/thực tập thực tế tại doanh nghiệp phù hợp.',
    weight: 1.0,
    status: 'Kích hoạt',
  },
  {
    id: 'cri-7',
    category: 'Chương trình đào tạo',
    groupName: 'Dịch vụ hỗ trợ Sinh viên',
    code: 'CTDT03',
    question: 'Nhà trường cung cấp đầy đủ các hoạt động tư vấn nghề nghiệp, hỗ trợ việc làm và nghiên cứu khoa học.',
    weight: 1.0,
    status: 'Kích hoạt',
  },
];

export const initialCampaigns: SurveyCampaign[] = [
  {
    id: 'cmp-1',
    title: 'Khảo sát Học phần Lập trình Web nâng cao (Lớp IT201.01)',
    type: 'Học phần',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    majorId: 'maj-1',
    majorName: 'Công nghệ Thông tin (Chuẩn)',
    courseId: 'crs-1',
    courseCode: 'IT201',
    courseName: 'Lập trình Web nâng cao & Đánh giá chất lượng',
    classId: 'cls-1',
    classCode: 'IT201.01',
    lecturerName: 'TS. Nguyễn Văn A',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    status: 'Đang diễn ra',
    targetAudience: 'Sinh viên Lớp IT201.01 - HK II 2025-2026',
    surveyLink: 'https://khaosat.vimaru.edu.vn/survey/cmp-1',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://khaosat.vimaru.edu.vn/survey/cmp-1',
    totalTargetResponses: 65,
    actualResponses: 58,
  },
  {
    id: 'cmp-2',
    title: 'Khảo sát Lấy ý kiến Sinh viên về Chương trình Đào tạo Khóa 63 (VMU)',
    type: 'Chương trình đào tạo',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    majorId: 'maj-1',
    majorName: 'Công nghệ Thông tin (Chuẩn)',
    startDate: '2026-04-15',
    endDate: '2026-07-15',
    status: 'Đang diễn ra',
    targetAudience: 'Sinh viên năm cuối chuẩn bị tốt nghiệp Khóa 63',
    surveyLink: 'https://khaosat.vimaru.edu.vn/survey/cmp-2',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://khaosat.vimaru.edu.vn/survey/cmp-2',
    totalTargetResponses: 3200,
    actualResponses: 1830,
  },
  {
    id: 'cmp-3',
    title: 'Khảo sát Học phần Cơ sở Dữ liệu (Lớp IT305.02)',
    type: 'Học phần',
    semester: 'Học kỳ II',
    academicYear: '2025-2026',
    majorId: 'maj-1',
    majorName: 'Công nghệ Thông tin (Chuẩn)',
    courseId: 'crs-2',
    courseCode: 'IT305',
    courseName: 'Cơ sở Dữ liệu Quan hệ & Phi quan hệ',
    classId: 'cls-2',
    classCode: 'IT305.02',
    lecturerName: 'ThS. Trần Thị B',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    status: 'Đang diễn ra',
    targetAudience: 'Sinh viên Lớp IT305.02 - HK II 2025-2026',
    surveyLink: 'https://khaosat.vimaru.edu.vn/survey/cmp-3',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://khaosat.vimaru.edu.vn/survey/cmp-3',
    totalTargetResponses: 70,
    actualResponses: 62,
  },
];
